{ pkgs, ... }:

{

programs.zsh = {
    enable = true;
    shellAliases = {
      ll = "ls -l";
      fetch = "fastfetch";
      nemod = "(nemo . &)  > /dev/null 2>&1";
      nix-clean = "sudo nix-collect-garbage -d && nix-collect-garbage -d && nix-store --gc && sudo nix-store --optimise";
      conf = "cd ~/nix-dotfiles/";
    };

    # Enable oh-my-zsh with some core plugins
    /* oh-my-zsh = {
      enable = true; # ctrl +r to get fzf is set here
      plugins = [ "git" "z" "fzf" ];
      # Do not set theme here, we load powerlevel10k manually
    }; */

    # Extra initialization appended to .zshrc
    initContent = /* bash */ ''
 
     # Load plugins installed via nixpkgs
      source ${pkgs.zsh-fast-syntax-highlighting}/share/zsh/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
      
      source ${pkgs.zsh-autosuggestions}/share/zsh-autosuggestions/zsh-autosuggestions.zsh
      ZSH_AUTOSUGGEST_STRATEGY=(history completion)


      source ${pkgs.zsh-fzf-tab}/share/fzf-tab/fzf-tab.plugin.zsh
      source ${pkgs.zsh-you-should-use}/share/zsh/plugins/you-should-use/you-should-use.plugin.zsh

      # Enable vi mode (ESC or Ctrl + [ to Enter)
      bindkey -v 
      export ZSH_SYSTEM_CLIPBOARD_USE_WL_CLIPBOARD="true"
      source ${pkgs.zsh-system-clipboard}/share/zsh/zsh-system-clipboard/zsh-system-clipboard.zsh
      

      export EDITOR="nvim"

      # SET fzf and fzf-tab pointer colour to #cba6f7

      export FZF_DEFAULT_OPTS="--color=POINTER:#cba6f7,HL+:#5fd7ff,HL:#5fd7ff"
      zstyle ':fzf-tab:*' fzf-flags $FZF_DEFAULT_OPTS # --bind=tab:accept

      # Give files/directories colours ( ↓↓  will fix undefined variable)
      zstyle ':completion:*' list-colors ''${(s.:.)LS_COLORS}

      # Binds CTRL + F to accept suggestion BUT only the next word
      bindkey '^F' forward-word

      # KEEPING THIS, MIGHT WANT IN THE FUTURE: Widget mapping on zsh-autosuggestions github README
      # Use PARTIAL_ACCEPT_WIDGETS so it activates when keybind is activated 
      # If we use SUGGEST_ACCEPT_WIDGETS instead it the keybind will accept all suggestions instead of only one
      # ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS+=(forward-word)

      # Load Powerlevel10k theme
      source ${pkgs.zsh-powerlevel10k}/share/zsh-powerlevel10k/powerlevel10k.zsh-theme

      # Load your saved Powerlevel10k config (generated by wizard or hand‑tuned)
      # Place p10k.zsh alongside this home.nix for reproducibility
      if [ -f ${./.p10k.zsh} ]; then
        source ${./.p10k.zsh}
      fi
      
      # Allow commenting on a zsh terminal
      setopt interactivecomments

      # Ctrl + Left/Arrow keys
      bindkey "^[[1;5C" forward-word
      bindkey "^[[1;5D" backward-word

      alias ls="eza"
      
      # Ctrl + E for completion
      bindkey -v "^E" end-of-line


      source ${pkgs.zsh-vi-mode}/share/zsh-vi-mode/zsh-vi-mode.plugin.zsh
      # Append a command directly
      # This fixes fzf ctrl + r not working after adding zsh vi mode plugin
      zvm_after_init_commands+=('source <(fzf --zsh)')

      export ZVM_SYSTEM_CLIPBOARD_ENABLED=true

    '';
  };

}
