{ config, pkgs, inputs, ... }:

let
  rosepinePurpleDark = pkgs.stdenv.mkDerivation {
    name = "rosepine-purple-dark";
    # if the file is local
    # src = ./modules/Rosepine-Purple-Dark;
    # if it is not, use this:
    src = pkgs.fetchurl {
      url = "https://github.com/Mrn157/Rosepine-Purple-Dark/archive/refs/tags/Release.tar.gz";
      hash = "sha256-VZPp7dCbKDAr3NXt4eqKgZMl2DZqv/TfkCiDsoQ1SQ8=";
    };

    # To fix the error > cp: missing destination file operand after ''
    sourceRoot = "Rosepine-Purple-Dark-Release/Rosepine-Purple-Dark";
    # Or use cp -r Rosepine-Purple-Dark/* $out/share/themes/Rosepine-Purple-Dark in installPhase
    # This works because after unpackPhase and sourceRoot is not set,
    # Nix will automatically pick the top directory of the ARCHIVE
    # (Which is Rosepine-Purple-Dark-Release)

    installPhase = ''
      mkdir -p $out/share/themes/Rosepine-Purple-Dark
      cp -r * $out/share/themes/Rosepine-Purple-Dark
    '';
  };
in 

{
  imports = [
    ./modules/foot/foot.nix
    ./modules/fastfetch/fastfetch.nix
    ./modules/hyprland/hyprland.nix
    ./modules/rofi/rofi.nix
    ./modules/waybar/waybar.nix
    ./modules/nvchad/nvchad.nix
    inputs.zen-browser.homeModules.beta
  ];
  modules.foot.enable = true;

  programs.zen-browser.enable = true;

  programs.btop = {
    enable = true;
  };

  programs.btop.settings = {
    color_theme = "horizon";
    theme_background = false;
  };

  # Remember this!!! a .keep will is generated in order to make Pictures/Screenshots which is needed for grim
  home.file."Pictures/Screenshots/.keep".text = "something";
  home.file."Pictures/wallpaper.jpg".source = ./modules/wallpaper.jpg;


  # Basic user info
  home.username = "mrn1";
  home.homeDirectory = "/home/mrn1";
  home.stateVersion = "25.05"; # match your system version

  dconf = {
      settings = {
          "org/cinnamon/desktop/applications/terminal" = {
              exec = "foot";
              # exec-arg = ""; # argument
          };
      };
  };

  # Zsh configuration
  programs.zsh = {
    enable = true;
    shellAliases = {
      ll = "ls -l";
      fetch = "fastfetch";
      nemod = "nemo . &";
      nix-clean = "sudo nix-collect-garbage -d && nix-store --gc && sudo nix-store --optimise && sudo rm -rf ~/.config/nvim_*";
    };

    # Enable oh-my-zsh with some core plugins
    oh-my-zsh = {
      enable = true; # ctrl +r to get fzf is set here
      plugins = [ "git" "z" "fzf" ];
      # Do not set theme here, we load powerlevel10k manually
    };

    # Extra initialization appended to .zshrc
    initExtra = ''
      # Load plugins installed via nixpkgs
      source ${pkgs.zsh-fast-syntax-highlighting}/share/zsh/site-functions/fast-syntax-highlighting.plugin.zsh
      source ${pkgs.zsh-autosuggestions}/share/zsh-autosuggestions/zsh-autosuggestions.zsh
      source ${pkgs.zsh-fzf-tab}/share/fzf-tab/fzf-tab.plugin.zsh
      source ${pkgs.zsh-you-should-use}/share/zsh/plugins/you-should-use/you-should-use.plugin.zsh
      export EDITOR="nvim"

      # SET fzf and fzf-tab pointer colour to #cba6f7

      export FZF_DEFAULT_OPTS="--color=POINTER:#cba6f7"
      zstyle ':fzf-tab:*' fzf-flags --color=POINTER:#cba6f7 # --bind=tab:accept

      ZSH_AUTOSUGGEST_STRATEGY=(history completion)
      # Binds CTRL + F to accept suggestion BUT only the next word
      bindkey '^F' forward-word

      # KEEPING THIS, MIGHT WANT IN THE FUTURE: Widget mapping on zsh-autosuggestions github README
      # Use PARTIAL_ACCEPT_WIDGETS so it activates when keybind is activated 
      # If we use SUGGEST_ACCEPT_WIDGETS instead it the keybind will accept all suggestions instead of only one
      # ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS+=(forward-word)

      # Load Powerlevel10k theme
      source ${pkgs.zsh-powerlevel10k}/share/zsh-powerlevel10k/powerlevel10k.zsh-theme

      # Load your saved Powerlevel10k config (generated by wizard or hand‑tuned)
      # Place p10k.zsh alongside this home.nix for reproducibility
      if [ -f ${./modules/p10k/.p10k.zsh} ]; then
        source ${./modules/p10k/.p10k.zsh}
      fi
    '';
  };

  # Install plugin packages and extras
  home.packages = with pkgs; [
    hyprpicker
    zsh-fast-syntax-highlighting
    zsh-autosuggestions
    zsh-fzf-tab
    zsh-powerlevel10k
    fzf
    zsh-you-should-use
    legcord
  ];

  # Example: you can add more programs here
  programs.git.enable = true;
  programs.bat.enable = true;
  programs.bash = {
    enable = true;
    bashrcExtra = ''
    if [[ "$(tty)" == "/dev/tty1" ]] && [[ -z "$DISPLAY" ]]; then
      exec Hyprland
      fi
    '';
  };

  home.pointerCursor = {
    gtk.enable = true;
    x11.enable = true;
    size = 22;
    name = "BreezeX-RosePine-Linux";
    package = pkgs.rose-pine-cursor;
  };

  gtk = {
    enable = true;
    theme = {
     name = "Rosepine-Purple-Dark";
     package = rosepinePurpleDark;
    };


    iconTheme = {
      name = "Dracula";
      package = pkgs.dracula-icon-theme;
    };

    gtk3.extraConfig = {
      gtk-application-prefer-dark-theme = true;
    };

    cursorTheme = {
      name = "BreezeX-RoséPine";
      package = pkgs.rose-pine-cursor;
      size = 22;
    };
  };
}

